"""empty message

Revision ID: 49578f8c70d7
Revises: 
Create Date: 2022-12-08 12:43:36.888006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49578f8c70d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('base_stat_hp', sa.Integer(), nullable=True),
    sa.Column('base_stat_defense', sa.Integer(), nullable=True),
    sa.Column('base_stat_attack', sa.Integer(), nullable=True),
    sa.Column('sprite', sa.String(), nullable=False),
    sa.Column('ability_name', sa.String(), nullable=True),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_name', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'pokemon', ['pokemon_name'], ['name'])
        batch_op.drop_column('pokemon_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pokemon_name')

    op.drop_table('pokemon')
    # ### end Alembic commands ###
